
import { Product, Category } from './types';

export const IMAGES = {
  COLARES: "https://lh3.googleusercontent.com/aida-public/AB6AXuA5WqeV3vcdo_CzyMovUn6UQVGt9AcCCdGWHMb6M2cckV6wsGIfYAHMidfHcpjd-_GLoIYrGfTrJW-B3orn4plBJO14auaw8OG9VAJXUUg50kzJlPmiy1lR0lWhz1YwTyFQUxGQIeRKhZU6CrkAr4HM-l13-RfB-EddmU23spod0J9adTJiY7iwDJpKWAO99MovajHoxxZZx3V6BkWrG_bWbhb8CtubVaQbtWPqrNAQ2SBYFX06pxd-1LHjqIN0kHFtUMNtZz_K-c5v",
  ANEIS: "https://lh3.googleusercontent.com/aida-public/AB6AXuDW3xfu5BIkTlJmAm96EmWA6epzzJdE12bykc5B-aQ4Msj0dcEZXgP9YtQpdtEMz6Pe6sfCwAcpJ7XsfrRg4BkNVZHxtN1QFVhLjf_D5rAdIyJ9kY6wUKIu_8tiMFOQ5w62lwMMcbxzoIjaNy53EKszr4XLv8Hr2LR6d5WUAMHb0pFmQH2ieRUwOu5GFGf08nzQxJmw2MwDhwSZjYoCFyuwAzA2U4msf_GLoXTs0Ptczxurbw3F7g_1dCR_yJeBKgZ4FZyP1lc3Ot6M",
  BRINCOS: "https://lh3.googleusercontent.com/aida-public/AB6AXuCtNTLFHmPFNl3FJ1GI7ajv6-fx9YLEHRBJRqWTlOnsfmOubbEp6R2r_A5wY7Ql2Ci0ouB9Sd8P0cEzdMcZbLOMnsWP7Y1T4BgD_SiSBvvrZUxkAhG1hLqwxi1zrwmA0psFC3Nw5bhRexeKNsJPcbomprNi4elYV566VANSatouMwfr31bs5NO-dNkoFzdiZb-btnVhWYnxRVyl66k4ZyCKxWIXe4s7vBWt0dBt2p0KAyZyGdR1EQN1_dfrHeiq9eNIieE06-8Uv0Lj",
  PULSEIRAS: "https://lh3.googleusercontent.com/aida-public/AB6AXuC-CH8cmQiOMrNcbhMckjBkh9M5376HtDIbvBurZiCl1opHHqVryJfz_blcOCP_DKXbIMG6MTqKDVUoa2TzJ_FfLd-Vv1Zo3xvoo9ya07vEGY7WZRCUk5ogFgMcGi0G2wOvcXZXIK-loPnAq7PXlpRf9Ft5UWcJGoibnU4HdyE76PlGrRO5lOnRKXZ0Jxu-Su9kyic3tjr6cwut3axsl_OXNCAerPA7xCX_ALkXpmhJ17apXLTgPeedl-xs5S5V7_YPWp7v9BCHwsgU",
  AMETISTA_BANNER: "https://lh3.googleusercontent.com/aida-public/AB6AXuAq4tX0DGakMfHSguEDznH9gNwYjgZhyqmGYAkBahdtkKDaTY2EBfDDxVFl0fbx8S0nFtsaIUmI9fqRRxYZmee7DDmkNefzcnxVTTTLmnSp8j5ZtHlcWzW_fiWantfTdgwL29D8xDB-gubKfMUKbGCahJGSqfL9wGltYblkFNorfdQGs_lgwcm_MorFS2HBVQtqsKjS1FzgMMoULIe-eDsvhHRo2D7FkSAhcYj3rTy7bwt8V5UUb4TZYKnVFZbPlQrFdsnsap87y17G",
  UNIQUE_1: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxczx9MIdqCWVPeyNhoaJOA3UrXiJqv2RrAQyyFxMWk1aAmb_aMGeBN4EC-VmzwQc6sudFeXeZm9_wwUsY4VnaT6if1U0Igqgw_H5VxgcloffVsK2T7cHcP-wHGnujwV_WP9e7jv0Lmcawasmy-oE21GYYsOMC_4gFoi5k3oLQydN9SmFPRRzryBu9_XAofLQZzTM1FMk-NZ4S-9yLLkHmqNjMigNd1qc7AUW4Lw-AvK48OD16DblSWYAnttIxXRjrjomc1Of8LJ5N",
  UNIQUE_2: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1TS9heXdVkvblAkSNhwJ4BxmTsQn_cNYDjcgBb7xJUhfMOT8rGt0gsuWjB4osH8WnPR8hDINMxgVSFhIHCWAXngvr0MjN6F7ojNg-GirIDBezA0J4UpY1rUjSHxxJ9L-DaUB4aXu91wq2xif928B7LCq9W0MnfGi3YCIdA0nMqtYCbPOIPNtkdgxj4PEm3kMqO5rGfCrvjl0MnGlLtQmLrgQHx3R1Nu53pgo_jEL7MEydciazVLcTdFYszfi_905kxUxkBKISt_Jf",
  HERO_BG: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=1920",
  PRODUCT_WHITE_1: "https://lh3.googleusercontent.com/aida-public/AB6AXuCxczx9MIdqCWVPeyNhoaJOA3UrXiJqv2RrAQyyFxMWk1aAmb_aMGeBN4EC-VmzwQc6sudFeXeZm9_wwUsY4VnaT6if1U0Igqgw_H5VxgcloffVsK2T7cHcP-wHGnujwV_WP9e7jv0Lmcawasmy-oE21GYYsOMC_4gFoi5k3oLQydN9SmFPRRzryBu9_XAofLQZzTM1FMk-NZ4S-9yLLkHmqNjMigNd1qc7AUW4Lw-AvK48OD16DblSWYAnttIxXRjrjomc1Of8LJ5N",
  PRODUCT_WHITE_2: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1TS9heXdVkvblAkSNhwJ4BxmTsQn_cNYDjcgBb7xJUhfMOT8rGt0gsuWjB4osH8WnPR8hDINMxgVSFhIHCWAXngvr0MjN6F7ojNg-GirIDBezA0J4UpY1rUjSHxxJ9L-DaUB4aXu91wq2xif928B7LCq9W0MnfGi3YCIdA0nMqtYCbPOIPNtkdgxj4PEm3kMqO5rGfCrvjl0MnGlLtQmLrgQHx3R1Nu53pgo_jEL7MEydciazVLcTdFYszfi_905kxUxkBKISt_Jf",
  PRODUCT_WHITE_3: "https://lh3.googleusercontent.com/aida-public/AB6AXuAq4tX0DGakMfHSguEDznH9gNwYjgZhyqmGYAkBahdtkKDaTY2EBfDDxVFl0fbx8S0nFtsaIUmI9fqRRxYZmee7DDmkNefzcnxVTTTLmnSp8j5ZtHlcWzW_fiWantfTdgwL29D8xDB-gubKfMUKbGCahJGSqfL9wGltYblkFNorfdQGs_lgwcm_MorFS2HBVQtqsKjS1FzgMMoULIe-eDsvhHRo2D7FkSAhcYj3rTy7bwt8V5UUb4TZYKnVFZbPlQrFdsnsap87y17G",
};

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Colares', description: 'Proteção perto do coração', imageUrl: IMAGES.COLARES },
  { id: '2', name: 'Anéis', description: 'Poder em suas mãos', imageUrl: IMAGES.ANEIS },
  { id: '3', name: 'Brincos', description: 'Clareza e intuição', imageUrl: IMAGES.BRINCOS },
  { id: '4', name: 'Pulseiras', description: 'Equilíbrio em movimento', imageUrl: IMAGES.PULSEIRAS },
];

export const HIGHLIGHT_PRODUCTS: Product[] = [
  { id: 'p1', name: 'Rubi da Proteção', category: 'Colares', description: 'O Rubi é conhecido como a pedra da paixão e vitalidade. Este colar foi desenhado para atuar como um escudo contra vampirismo energético, trazendo coragem para enfrentar desafios diários e fortalecendo o chakra do coração.', price: 289, originalPrice: 350, isSale: true, imageUrl: IMAGES.PRODUCT_WHITE_1, colorName: 'Rubi Profundo', colorCode: '#9b111e', sku: 'NS-RB-001', tags: ['Proteção', 'Vitalidade'], rating: 4.8, reviewsCount: 124, inStock: true },
  { id: 'p2', name: 'Raio de Luz', category: 'Colares', description: 'Uma ametista lapidada para maximizar a reflexão da luz divina. Ideal para momentos de meditação profunda e busca por clareza espiritual. Este colar ajuda na transmutação de pensamentos densos em vibrações elevadas.', price: 345, imageUrl: IMAGES.PRODUCT_WHITE_2, colorName: 'Ametista Clara', colorCode: '#dfc5fe', sku: 'NS-RL-002', tags: ['Divino', 'Paz'], rating: 4.9, reviewsCount: 88, inStock: true },
  { id: 'p3', name: 'Iluminação Celestial', category: 'Acessórios', description: 'Inspirado no céu do amanhecer, este acessório traz a energia do azul celeste para acalmar mentes agitadas e promover a comunicação clara com o eu superior.', price: 199, originalPrice: 249, isSale: true, imageUrl: IMAGES.PRODUCT_WHITE_3, colorName: 'Azul Celeste', colorCode: '#87ceeb', sku: 'NS-IC-003', tags: ['Serenidade', 'Foco'], rating: 4.7, reviewsCount: 56, inStock: true },
];

export const BEST_SELLERS: Product[] = [
  { id: 'bs1', name: 'Anel de Quartzo Rosa', category: 'Anéis', description: 'A pedra fundamental do amor incondicional. Este anel de Quartzo Rosa emana uma energia suave de cura emocional, ajudando no perdão e na aceitação de si mesmo. Perfeito para quem busca equilíbrio nos relacionamentos.', price: 159, originalPrice: 210, isSale: true, imageUrl: IMAGES.ANEIS, colorName: 'Rosa Quartzo', colorCode: '#f7d1d1', sku: 'NS-QR-011', tags: ['Amor', 'Cura'], rating: 4.8, reviewsCount: 245, inStock: true },
  { id: 'bs2', name: 'Colar de Água Marinha', category: 'Colares', description: 'Símbolo da juventude eterna e felicidade, a Água Marinha protege a aura e alinha os chakras, limpando o chakra da garganta e trazendo comunicações inspiradas.', price: 210, imageUrl: IMAGES.COLARES, colorName: 'Água Marinha', colorCode: '#7fffd4', sku: 'NS-AM-012', tags: ['Clareza', 'Paz'], rating: 4.9, reviewsCount: 132, inStock: true },
  { id: 'bs3', name: 'Brincos de Citrino', category: 'Brincos', description: 'O Citrino é a pedra da abundância e do otimismo. Estes brincos carregam a energia solar necessária para manifestar prosperidade e alegria em todos os aspectos da vida.', price: 180, originalPrice: 220, isSale: true, imageUrl: IMAGES.BRINCOS, colorName: 'Citrino Dourado', colorCode: '#e4d00a', sku: 'NS-CT-013', tags: ['Alegria', 'Riqueza'], rating: 4.6, reviewsCount: 94, inStock: true },
  { id: 'bs4', name: 'Pulseira de Turmalina', category: 'Pulseiras', description: 'A Turmalina Negra é a maior protetora contra ataques psíquicos e radiações eletromagnéticas. Esta pulseira cria um campo de força invisível ao redor de quem a usa.', price: 145, imageUrl: IMAGES.PULSEIRAS, colorName: 'Negro Turmalina', colorCode: '#000000', sku: 'NS-TR-014', tags: ['Proteção'], rating: 5.0, reviewsCount: 210, inStock: true },
  { id: 'bs5', name: 'Colar de Lápis Lazúli', category: 'Colares', description: 'Conhecida como a pedra dos faraós, o Lápis Lazúli estimula a iluminação e aumenta o trabalho com sonhos e as capacidades psíquicas, facilitando a viagem espiritual.', price: 275, originalPrice: 320, isSale: true, imageUrl: IMAGES.PRODUCT_WHITE_1, colorName: 'Azul Lápis', colorCode: '#263238', sku: 'NS-LL-015', tags: ['Verdade', 'Sabedoria'], rating: 4.8, reviewsCount: 67, inStock: true },
  { id: 'bs6', name: 'Anel de Granada', category: 'Anéis', description: 'A Granada é uma pedra revitalizante que regenera o corpo e estimula o metabolismo. Este anel traz paixão e compromisso para a vida cotidiana.', price: 195, imageUrl: IMAGES.ANEIS, colorName: 'Vermelho Granada', colorCode: '#7b1113', sku: 'NS-GR-016', tags: ['Paixão'], rating: 4.7, reviewsCount: 43, inStock: true },
  { id: 'bs7', name: 'Brincos de Ametista', category: 'Brincos', description: 'A pedra da espiritualidade e da sobriedade. Estes brincos ajudam a controlar vícios emocionais e promovem uma noite de sono reparadora e sonhos lúcidos.', price: 165, originalPrice: 200, isSale: true, imageUrl: IMAGES.PRODUCT_WHITE_3, colorName: 'Roxo Real', colorCode: '#7851a9', sku: 'NS-AM-017', tags: ['Paz', 'Espiritual'], rating: 4.9, reviewsCount: 156, inStock: true },
  { id: 'bs8', name: 'Pulseira de Olho de Tigre', category: 'Pulseiras', description: 'Uma pedra protetora que tradicionalmente era usada como talismã contra maldições e quebrantos. Ajuda a focar a mente e resolver dilemas e conflitos internos.', price: 130, imageUrl: IMAGES.PULSEIRAS, colorName: 'Mel Âmbar', colorCode: '#b36d00', sku: 'NS-OT-018', tags: ['Foco', 'Solar'], rating: 4.8, reviewsCount: 112, inStock: true },
];

export const CHAKRA_COLLECTION: Product[] = [
  { id: 'ch1', name: 'Colar Raiz', category: 'Chakras', description: 'Baseado no Jaspe Vermelho, este colar promove o aterramento e a segurança. É a base para que todas as outras energias fluam com estabilidade no seu corpo físico.', price: 189, imageUrl: IMAGES.PRODUCT_WHITE_1, colorName: 'Jaspe Vermelho', colorCode: '#ff0000', sku: 'NS-CH-101', tags: ['Raiz', 'Aterramento'], rating: 4.7, reviewsCount: 45, inStock: true },
  { id: 'ch2', name: 'Anel Sacral', category: 'Chakras', description: 'Equilibra o centro da criatividade e do prazer. A Cornalina presente neste anel estimula a coragem para novas experiências e o fluxo de emoções saudáveis.', price: 165, originalPrice: 199, isSale: true, imageUrl: IMAGES.ANEIS, colorName: 'Cornalina', colorCode: '#ff7f00', sku: 'NS-CH-102', tags: ['Criatividade'], rating: 4.8, reviewsCount: 32, inStock: true },
  { id: 'ch3', name: 'Brincos do Plexo', category: 'Chakras', description: 'Fortalece a autoconfiança e o poder pessoal. Estes brincos ajudam a dissipar medos e a tomar as rédeas da própria vida com clareza e determinação solar.', price: 178, imageUrl: IMAGES.BRINCOS, colorName: 'Citrino', colorCode: '#ffff00', sku: 'NS-CH-103', tags: ['Poder'], rating: 4.9, reviewsCount: 28, inStock: true },
  { id: 'ch4', name: 'Colar do Coração', category: 'Chakras', description: 'Abertura para o amor incondicional e a compaixão. Este colar de Quartzo Verde limpa mágoas antigas e prepara o coração para conexões verdadeiras.', price: 210, originalPrice: 280, isSale: true, imageUrl: IMAGES.COLARES, colorName: 'Quartzo Verde', colorCode: '#00ff00', sku: 'NS-CH-104', tags: ['Amor'], rating: 5.0, reviewsCount: 64, inStock: true },
  { id: 'ch5', name: 'Pulseira da Garganta', category: 'Chakras', description: 'Promove a expressão da verdade com gentileza. A Sodalita nesta pulseira facilita a comunicação de pensamentos complexos e a escuta ativa.', price: 145, imageUrl: IMAGES.PULSEIRAS, colorName: 'Sodalita', colorCode: '#0000ff', sku: 'NS-CH-105', tags: ['Comunicação'], rating: 4.7, reviewsCount: 19, inStock: true },
];

export const PROTECTION_COLLECTION: Product[] = [
  { id: 'pr1', name: 'Escudo de Ônix', category: 'Proteção', description: 'O Ônix é a pedra da força e do autocontrole. Este colar atua como uma armadura para o plexo solar, impedindo que influências externas drenem sua energia vital.', price: 245, originalPrice: 299, isSale: true, imageUrl: IMAGES.PRODUCT_WHITE_2, colorName: 'Ônix Negro', colorCode: '#111111', sku: 'NS-PR-201', tags: ['Escudo'], rating: 4.8, reviewsCount: 77, inStock: true },
  { id: 'pr2', name: 'Colar de Selenita', category: 'Proteção', description: 'A Selenita é autolimpante. Este colar não só protege você como também limpa outros cristais ao seu redor, mantendo sua aura brilhante e translúcida.', price: 189, imageUrl: IMAGES.COLARES, colorName: 'Branco Puro', colorCode: '#ffffff', sku: 'NS-PR-202', tags: ['Limpeza'], rating: 4.9, reviewsCount: 89, inStock: true },
  { id: 'pr3', name: 'Anel de Hematita', category: 'Proteção', description: 'A Hematita é excelente para o aterramento. Este anel ajuda a manter o foco no presente e protege contra energias desequilibrantes em ambientes movimentados.', price: 135, imageUrl: IMAGES.ANEIS, colorName: 'Cinza Metálico', colorCode: '#707070', sku: 'NS-PR-203', tags: ['Foco'], rating: 4.6, reviewsCount: 42, inStock: true },
  { id: 'pr4', name: 'Brincos de Pirita', category: 'Proteção', description: 'Conhecida como o ouro dos tolos, a Pirita é na verdade um escudo protetor contra o perigo físico e um imã para o sucesso material e intelectual.', price: 198, originalPrice: 250, isSale: true, imageUrl: IMAGES.BRINCOS, colorName: 'Dourado Brilhante', colorCode: '#ffd700', sku: 'NS-PR-204', tags: ['Riqueza'], rating: 4.8, reviewsCount: 55, inStock: true },
  { id: 'pr5', name: 'Pulseira de Labradorita', category: 'Proteção', description: 'Pedra de magia e transformação. Esta pulseira fortalece a intuição e protege contra perdas de energia por furos na aura durante processos de mudança.', price: 220, imageUrl: IMAGES.PULSEIRAS, colorName: 'Reflexos Místicos', colorCode: '#5b84b1', sku: 'NS-PR-205', tags: ['Magia'], rating: 4.9, reviewsCount: 38, inStock: true },
];
